%global tl_name metaplot
%global tl_revision 79618

Name:		texlive-%{tl_name}
Epoch:		1
Version:	0.91
Release:	%{tl_revision}.1
Summary:	Plot-manipulation macros for use in MetaPost
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/graphics/metaplot
License:	lppl1.3
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/metaplot.r%{tl_revision}.tar.xz
Source1:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/metaplot.doc.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
MetaPlot is a set of MetaPost macros for manipulating pre-generated
plots (and similar objects), and formatting them for inclusion in a
MetaPost figure. The intent is that the plots can be generated by some
outside program, in an abstract manner that does not require making
decisions about on-page sizing and layout, and then they can be imported
into MetaPlot and arranged using the full capabilities of MetaPost.
Metaplot also includes a very flexible set of macros for generating plot
axes, which may be useful in other contexts as well. Presently, MetaPlot
is in something of a pre-release beta state; it is quite functional, but
the syntax of the commands is still potentially in flux.

