Name:		texlive-metaplot
Version:	15878
Release:	2
Summary:	Plot-manipulation macros for use in Metapost
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/graphics/metaplot
License:	LPPL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/metaplot.r%{version}.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/metaplot.doc.r%{version}.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
MetaPlot is a set of Metapost macros for manipulating pre-
generated plots (and similar objects), and formatting them for
inclusion in a Metapost figure. The intent is that the plots
can be generated by some outside program, in an abstract manner
that does not require making decisions about on-page sizing and
layout, and then they can be imported into MetaPlot and
arranged using the full capabilities of Metapost. Metaplot also
includes a very flexible set of macros for generating plot
axes, which may be useful in other contexts as well. Presently,
MetaPlot is in something of a pre-release beta state; it is
quite functional, but the syntax of the commands are still
potentially in flux. Bug reports and other suggestions would be
most welcome!.

%post
%{_sbindir}/texlive.post

%postun
if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/metapost/metaplot/axes.mp
%{_texmfdistdir}/metapost/metaplot/metaplot.mp
%doc %{_texmfdistdir}/doc/latex/metaplot/README
%doc %{_texmfdistdir}/doc/latex/metaplot/examples/cap1.cc
%doc %{_texmfdistdir}/doc/latex/metaplot/examples/cap1.mp
%doc %{_texmfdistdir}/doc/latex/metaplot/examples/capillary.cc
%doc %{_texmfdistdir}/doc/latex/metaplot/examples/cpoint.cc
%doc %{_texmfdistdir}/doc/latex/metaplot/examples/cpoint.h
%doc %{_texmfdistdir}/doc/latex/metaplot/examples/figure_1.mp
%doc %{_texmfdistdir}/doc/latex/metaplot/examples/figures_2-7.mp
%doc %{_texmfdistdir}/doc/latex/metaplot/examples/figures_8-9.mp
%doc %{_texmfdistdir}/doc/latex/metaplot/examples/gpl.txt
%doc %{_texmfdistdir}/doc/latex/metaplot/examples/mc2.mp
%doc %{_texmfdistdir}/doc/latex/metaplot/examples/metacontour.cc
%doc %{_texmfdistdir}/doc/latex/metaplot/examples/metacontour.h
%doc %{_texmfdistdir}/doc/latex/metaplot/examples/metacontour_main.cc
%doc %{_texmfdistdir}/doc/latex/metaplot/metaplot_preprint.pdf

#-----------------------------------------------------------------------
%prep
%autosetup -p1 -c -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar metapost doc %{buildroot}%{_texmfdistdir}
